---
- :name: Roses
  :code: R12
  :bundles:
    - :size: 5
      :price: 699
    - :size: 10
      :price: 1299
- :name: Lilies
  :code: L09
  :bundles:
    - :size: 3
      :price: 995
    - :size: 6
      :price: 1695
    - :size: 9
      :price: 2495
- :name: Tulips
  :code: T58
  :bundles:
    - :size: 3
      :price: 595
    - :size: 5
      :price: 995
    - :size: 9
      :price: 1699
